// frontend/web/src/components/layouts/Footer.vue
<template>
  <footer class="bg-gray-900 text-gray-300">
    <div class="container mx-auto px-4 py-12">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div>
          <h3 class="text-white text-lg font-semibold mb-4">Masjid Al-Madr</h3>
          <p class="text-sm mb-4">
            Pusat kegiatan keagamaan dan sosial masyarakat yang berkomitmen
            untuk membangun komunitas yang harmonis dan berkualitas.
          </p>
        </div>
        <div>
          <h3 class="text-white text-lg font-semibold mb-4">Kontak</h3>
          <ul class="space-y-3 text-sm">
            <li class="flex items-start gap-2">
              <span class="inline-block w-5 h-5 rounded bg-gray-700 flex-shrink-0" />
              Jl. Masjid Raya No. 123, Jakarta Selatan
            </li>
            <li class="flex items-center gap-2">
              <span class="inline-block w-5 h-5 rounded bg-gray-700 flex-shrink-0" />
              <a href="tel:+62123456789" class="hover:text-white">+62 123 456 789</a>
            </li>
            <li class="flex items-center gap-2">
              <span class="inline-block w-5 h-5 rounded bg-gray-700 flex-shrink-0" />
              <a href="mailto:info@masjidalmadr.com" class="hover:text-white"
                >info@masjidalmadr.com</a
              >
            </li>
          </ul>
        </div>
        <div>
          <h3 class="text-white text-lg font-semibold mb-4">Tautan</h3>
          <ul class="space-y-2 text-sm">
            <li>
              <router-link to="/" class="hover:text-white transition-colors"
                >Beranda</router-link
              >
            </li>
            <li>
              <router-link to="/donate" class="hover:text-white transition-colors"
                >Donasi</router-link
              >
            </li>
            <li>
              <router-link to="/contact" class="hover:text-white transition-colors"
                >Kontak</router-link
              >
            </li>
          </ul>
          <div class="mt-6 flex gap-4">
            <a
              href="https://facebook.com"
              target="_blank"
              rel="noopener noreferrer"
              class="hover:text-white transition-colors"
              aria-label="Facebook"
              >Facebook</a
            >
            <a
              href="https://instagram.com"
              target="_blank"
              rel="noopener noreferrer"
              class="hover:text-white transition-colors"
              aria-label="Instagram"
              >Instagram</a
            >
            <a
              href="https://youtube.com"
              target="_blank"
              rel="noopener noreferrer"
              class="hover:text-white transition-colors"
              aria-label="YouTube"
              >YouTube</a
            >
          </div>
        </div>
      </div>
      <div class="mt-8 pt-8 border-t border-gray-800">
        <a
          href="https://wa.me/62123456789"
          target="_blank"
          rel="noopener noreferrer"
          class="inline-flex items-center gap-2 bg-green-500 hover:bg-green-600 text-white px-6 py-3 rounded-lg transition-colors"
        >
          Hubungi via WhatsApp
        </a>
      </div>
      <div class="mt-8 pt-8 border-t border-gray-800 text-center text-sm">
        <p>&copy; {{ new Date().getFullYear() }} Masjid Al-Madr. All rights reserved.</p>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
</script>

// frontend/web/components/layouts/footer.tsx
import Link from "next/link";
import { Phone, Mail, MapPin, Facebook, Instagram, Youtube } from "lucide-react";

export function Footer() {
  return (
    <footer className="bg-gray-900 text-gray-300">
      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* About */}
          <div>
            <h3 className="text-white text-lg font-semibold mb-4">
              Masjid Al-Madr
            </h3>
            <p className="text-sm mb-4">
              Pusat kegiatan keagamaan dan sosial masyarakat yang berkomitmen
              untuk membangun komunitas yang harmonis dan berkualitas.
            </p>
          </div>

          {/* Contact Info */}
          <div>
            <h3 className="text-white text-lg font-semibold mb-4">Kontak</h3>
            <ul className="space-y-3 text-sm">
              <li className="flex items-start">
                <MapPin className="w-5 h-5 mr-2 mt-0.5 flex-shrink-0" />
                <span>Jl. Masjid Raya No. 123, Jakarta Selatan</span>
              </li>
              <li className="flex items-center">
                <Phone className="w-5 h-5 mr-2 flex-shrink-0" />
                <a href="tel:+62123456789" className="hover:text-white">
                  +62 123 456 789
                </a>
              </li>
              <li className="flex items-center">
                <Mail className="w-5 h-5 mr-2 flex-shrink-0" />
                <a href="mailto:info@masjidalmadr.com" className="hover:text-white">
                  info@masjidalmadr.com
                </a>
              </li>
            </ul>
          </div>

          {/* Quick Links */}
          <div>
            <h3 className="text-white text-lg font-semibold mb-4">Tautan</h3>
            <ul className="space-y-2 text-sm">
              <li>
                <Link href="/" className="hover:text-white transition-colors">
                  Beranda
                </Link>
              </li>
              <li>
                <Link href="/donate" className="hover:text-white transition-colors">
                  Donasi
                </Link>
              </li>
              <li>
                <Link href="/contact" className="hover:text-white transition-colors">
                  Kontak
                </Link>
              </li>
            </ul>

            {/* Social Media */}
            <div className="mt-6 flex space-x-4">
              <a
                href="https://facebook.com"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-white transition-colors"
                aria-label="Facebook"
              >
                <Facebook className="w-5 h-5" />
              </a>
              <a
                href="https://instagram.com"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-white transition-colors"
                aria-label="Instagram"
              >
                <Instagram className="w-5 h-5" />
              </a>
              <a
                href="https://youtube.com"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-white transition-colors"
                aria-label="YouTube"
              >
                <Youtube className="w-5 h-5" />
              </a>
            </div>
          </div>
        </div>

        {/* WhatsApp Button */}
        <div className="mt-8 pt-8 border-t border-gray-800">
          <a
            href="https://wa.me/62123456789"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center bg-green-500 hover:bg-green-600 text-white px-6 py-3 rounded-lg transition-colors"
          >
            <Phone className="w-5 h-5 mr-2" />
            Hubungi via WhatsApp
          </a>
        </div>

        {/* Copyright */}
        <div className="mt-8 pt-8 border-t border-gray-800 text-center text-sm">
          <p>&copy; {new Date().getFullYear()} Masjid Al-Madr. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}
