// frontend/web/src/components/sections/HeroSection.vue
<template>
  <section class="relative min-h-screen flex items-center justify-center overflow-hidden">
    <div class="absolute inset-0 z-0">
      <video v-if="heroBanner?.type === 'video' && mediaUrl" autoplay muted loop playsinline class="w-full h-full object-cover">
        <source :src="mediaUrl" type="video/mp4" />
      </video>
      <div v-else class="w-full h-full bg-cover bg-center" :style="bgStyle"></div>
      <div class="absolute inset-0 bg-black/50"></div>
    </div>
    <div class="relative z-10 container mx-auto px-4 text-center text-white">
      <h1 class="text-4xl md:text-6xl lg:text-7xl font-bold mb-6">Masjid Al-Madr</h1>
      <p class="text-lg md:text-xl lg:text-2xl mb-8 text-gray-200">Pusat Kegiatan Keagamaan dan Sosial Masyarakat</p>
      <router-link to="/donate" class="inline-flex items-center justify-center px-8 py-6 text-lg rounded-lg bg-primary text-primary-foreground hover:opacity-90">Donasi Sekarang</router-link>
    </div>
    <div class="absolute bottom-8 left-1/2 -translate-x-1/2 z-10">
      <div class="w-6 h-10 border-2 border-white rounded-full flex items-start justify-center p-2"><div class="w-1 h-3 bg-white rounded-full"></div></div>
    </div>
  </section>
</template>
<script setup lang="ts">
import { computed, ref, onMounted } from 'vue'
import { bannerApi } from '@/api/banners'
import type { PaginatedResponse } from '@/api/client'
import type { Banner } from '@/api/banners'
import { resolveMediaUrl } from '@/utils/media'

const banners = ref<PaginatedResponse<Banner> | null>(null)
const heroBanner = computed(() => banners.value?.data?.[0])
const mediaUrl = computed(() => heroBanner.value?.media_url ? resolveMediaUrl(heroBanner.value.media_url) : undefined)
const bgStyle = computed(() => ({ backgroundImage: heroBanner.value && mediaUrl.value ? 'url(' + mediaUrl.value + ')' : 'linear-gradient(to bottom, #1e3a8a, #3b82f6)' }))
onMounted(async () => { banners.value = await bannerApi.getAll(1, 0) })
</script>

// frontend/web/components/sections/hero-section.tsx
"use client";

import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { bannerApi } from "@/lib/api/banners";

export function HeroSection() {
  const { data: banners } = useQuery({
    queryKey: ["banners"],
    queryFn: () => bannerApi.getAll(1, 0),
  });

  const heroBanner = banners?.data?.[0];

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
      {/* Background Video/Image */}
      <div className="absolute inset-0 z-0">
        {heroBanner?.type === "video" ? (
          <video
            autoPlay
            muted
            loop
            playsInline
            className="w-full h-full object-cover"
          >
            <source src={heroBanner.media_url} type="video/mp4" />
          </video>
        ) : (
          <div
            className="w-full h-full bg-cover bg-center"
            style={{
              backgroundImage: heroBanner
                ? `url(${heroBanner.media_url})`
                : "linear-gradient(to bottom, #1e3a8a, #3b82f6)",
            }}
          />
        )}
        {/* Overlay */}
        <div className="absolute inset-0 bg-black/50" />
      </div>

      {/* Content */}
      <div className="relative z-10 container mx-auto px-4 text-center text-white">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="max-w-4xl mx-auto"
        >
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.8 }}
            className="text-4xl md:text-6xl lg:text-7xl font-bold mb-6"
          >
            Masjid Al-Madr
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.8 }}
            className="text-lg md:text-xl lg:text-2xl mb-8 text-gray-200"
          >
            Pusat Kegiatan Keagamaan dan Sosial Masyarakat
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6, duration: 0.8 }}
          >
            <Button
              asChild
              size="lg"
              className="bg-primary hover:bg-primary/90 text-white px-8 py-6 text-lg"
            >
              <Link href="/donate">Donasi Sekarang</Link>
            </Button>
          </motion.div>
        </motion.div>
      </div>

      {/* Scroll Indicator */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1, duration: 0.8 }}
        className="absolute bottom-8 left-1/2 transform -translate-x-1/2 z-10"
      >
        <motion.div
          animate={{ y: [0, 10, 0] }}
          transition={{ repeat: Infinity, duration: 1.5 }}
          className="w-6 h-10 border-2 border-white rounded-full flex items-start justify-center p-2"
        >
          <motion.div
            animate={{ y: [0, 12, 0] }}
            transition={{ repeat: Infinity, duration: 1.5 }}
            className="w-1 h-3 bg-white rounded-full"
          />
        </motion.div>
      </motion.div>
    </section>
  );
}
