// frontend/web/components/sections/gallery-section.tsx
"use client";

import { motion } from "framer-motion";
import { useQuery } from "@tanstack/react-query";
import { galleryApi } from "@/lib/api/gallery";
import Image from "next/image";

export function GallerySection() {
  const { data: galleryData, isLoading } = useQuery({
    queryKey: ["gallery"],
    queryFn: () => galleryApi.getAll(12, 0),
  });

  const galleryItems = galleryData?.data || [];

  if (isLoading) {
    return (
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <p className="text-center text-gray-600">Memuat galeri...</p>
        </div>
      </section>
    );
  }

  if (galleryItems.length === 0) {
    return null;
  }

  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Galeri Foto
          </h2>
          <p className="text-lg text-gray-600">
            Dokumentasi kegiatan dan aktivitas masjid
          </p>
        </motion.div>

        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {galleryItems.map((item, index) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.05 }}
              whileHover={{ scale: 1.05 }}
              className="relative aspect-square rounded-lg overflow-hidden cursor-pointer group"
            >
              <Image
                src={item.image_url}
                alt={item.title}
                fill
                className="object-cover transition-transform duration-300 group-hover:scale-110"
                sizes="(max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
              />
              <div className="absolute inset-0 bg-black/0 group-hover:bg-black/50 transition-colors duration-300 flex items-center justify-center">
                <p className="text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300 text-sm font-medium px-4 text-center">
                  {item.title}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

// frontend/web/src/components/sections/GallerySection.vue
<template>
  <section v-if="items.length > 0 || isLoading" class="py-20 bg-white">
    <div class="container mx-auto px-4">
      <div class="text-center mb-12">
        <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Galeri Foto</h2>
        <p class="text-lg text-gray-600">Dokumentasi kegiatan dan aktivitas masjid</p>
      </div>
      <p v-if="isLoading" class="text-center text-gray-600">Memuat galeri...</p>
      <div v-else class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <div v-for="item in items" :key="item.id" class="relative aspect-square rounded-lg overflow-hidden group">
          <img :src="imgUrl(item.image_url)" :alt="item.title" class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110" />
          <div class="absolute inset-0 bg-black/0 group-hover:bg-black/50 transition-colors duration-300 flex items-center justify-center">
            <p class="text-white opacity-0 group-hover:opacity-100 transition-opacity text-sm font-medium px-4 text-center">{{ item.title }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { galleryApi } from '@/api/gallery'
import type { GalleryItem } from '@/api/gallery'
import { resolveMediaUrl } from '@/utils/media'
const items = ref<GalleryItem[]>([])
const isLoading = ref(true)
function imgUrl(url: string) {
  return url.startsWith('http') ? url : resolveMediaUrl(url)
}
onMounted(async () => {
  try { const res = await galleryApi.getAll(12, 0); items.value = res.data || [] } finally { isLoading.value = false }
})
</script>
